
image: "registry.gitlab.com/dangrenier/reap20/testing:v2"

variables:
  LC_ALL: C.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  RAILS_ENV: "test"
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  SELENIUM_URL: "http://selenium__standalone-chrome:4444/wd/hub"  


.default-cache: &default-cache
  cache:
    untracked: true
    key: reap20-key  
    paths:
      - node_modules/
      - vendor/
      - public

build:
  <<: *default-cache      
  services:
    - postgres:11.6
  stage: build 
    
  script:
    - ruby -v
    - node -v 
    - yarn --version 
    - which ruby 
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor
    - yarn install
    - cp config/database.yml.gitlab config/database.yml
    - RAILS_ENV=test bundle exec rake db:create db:schema:load db:seed 
    - RAILS_ENV=test bundle exec rails assets:precompile
  

rspec:
  <<: *default-cache
  stage: test
  services:
    - postgres:11.6
    - selenium/standalone-chrome:latest
  script:
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor
    - export selenium_remote_url="http://selenium__standalone/chrome:4444/wd/hub/"
    - RAILS_ENV=test bundle exec rake db:create db:schema:load db:seed 
    - RAILS_ENV=test bundle exec rails assets:precompile
    - RAILS_ENV=test bundle exec rails webpacker:compile
    - RAILS_ENV=test HEADLESS=true bundle exec rspec --format progress  
  artifacts:
    when: on_failure
    paths:
      - tmp/screenshots