stages:
  - build
  - test

.build:
  image: "ruby:2.6.4"
  cache:
    key: rat-app-name
    paths:
      -apt-cache/
      -vendor/ruby
      -node_modules/
    policy: pull  
  before_scripts:
    - gem install bundler --no_document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" -- path=vendor

.db:
  extends: .build
  services:  
    - postgres:11.6

  variables:
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
    DB_USERNAME: runner
    DB_PASSWORD: ""
    DB_HOST: postgres 
    RAILS_ENV: test 
    DISABLE_SPRING: 1
    BUNDLE_PATH: vendor/bundle
  before_script:
      

before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
  - ruby -v
  - which ruby 
  - gem install bundler --no-document
  - RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
  - cp config/database.yml.gitlab config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load --trace

rspec:
  extends: .db 
  stage: test
  cache:
    policy: pull-push
  script:
    - RAILS_ENV=test bundle exec rspec --format progress  